#!/usr/bin/env python3


import sys


if len(sys.argv) <=1 :#On vérifie qu'on a bien un paramètre.
	print("\t####################################")
	print("\tUn fichier au format csv est attendu en argument")
	print("\t####################################")
else:
	file = open(sys.argv[1], 'r')
	table_plant = open("table_plant.csv", 'w')
	table_mesure = open("table_mesure.csv", 'w')
	file.readline()
	for ligne in file.readlines():
		data=ligne.split(";")
		table_plant.write(data[3]+";"+data[8]+";"+data[9]+";"+data[2]+";"+data[0]+";"+data[1]+"\n")
		for i in [4,5,6,7,10,11]:
			table_mesure.write(str(i)+";"+data[3]+";"+data[i]+"\n")
		table_mesure.write(str(12)+";"+data[3]+";"+data[12])

	file.close()
	table_plant.close()
	table_mesure.close()